# Generated by Django 4.1 on 2023-06-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(blank=True, null=True, upload_to='')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.destination')),
            ],
        ),
    ]
